n_ffts = 2048
n_step = 512
n_wins = 1024
n_mels = 64
n_mfcc = 20
y_scale = True
y_mono = True
sr = 22050
win_size = 8
step_size = 4
num_pc = 10
svm_cost = 1
svm_type = 0
svm_kernel = 0
path_train = "/data/CS_MOTORNOISE_DATA"
path_test = "/data/CS_MORTORNOISE_TEST_DATA"
# scaler_model = "scaler.pkl"
# pca_model = "pca_fitted.pkl"
svm_model = "/data/total_file_pca_svm_trained.model"
vib_svm_model = "/data/vib_svm_trained.model"
vib_sr = 2048
audio_loader = ["java", "-jar", "/data/AudioLoader_New.jar"]
pca_loader = ["java", "-jar", "/data/PCA.jar"]
resample_result_path = "/data/resample_result"
num_components = 20 # -> 50 변경 테스트 필요
pca_data_path = "/data/before_pca.txt"
